name: DevSecOps Push Checks

on:
  push:
    branches:
      - '**'          # toutes les branches (feature/*, bugfix/*, master, etc.)
    # si tu veux ignorer les tags :
    # tags-ignore:
    #   - '*'

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (CI)
        run: npm ci

      - name: Lint (optional)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script, skipping."
          fi

      - name: Build
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script, skipping."
          fi

      - name: Unit tests
        run: npm test --silent

  sast-semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v4
      - name: Install Semgrep
        run: pipx install semgrep
      - name: Run Semgrep (OWASP Top 10)
        run: |
          semgrep --config p/owasp-top-ten --error --timeout 120 .

  sca-trivy:
    name: SCA (Trivy dependencies)
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy-archive-keyring.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: Trivy FS scan (HIGH,CRITICAL)
        run: trivy fs --security-checks vuln --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed .

  secrets-gitleaks:
    name: Secrets (Gitleaks)
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact --exit-code 1
